baseURL = "https://bestwish.es/"
languageCode = "en-us"
title = "BestWish.es"
themeDir = "themes"

[pagination]
pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
